// Code generated by mockery v1.0.0. DO NOT EDIT.

package runnerpoolmock

import (
	context "context"

	runnerpool "github.com/cabify/runnerpool"
	mock "github.com/stretchr/testify/mock"
)

// Pool is an autogenerated mock type for the Pool type
type Pool struct {
	mock.Mock
}

// Stats provides a mock function with given fields:
func (_m *Pool) Stats() runnerpool.Stats {
	ret := _m.Called()

	var r0 runnerpool.Stats
	if rf, ok := ret.Get(0).(func() runnerpool.Stats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(runnerpool.Stats)
	}

	return r0
}

// Worker provides a mock function with given fields: ctx
func (_m *Pool) Worker(ctx context.Context) (runnerpool.Worker, error) {
	ret := _m.Called(ctx)

	var r0 runnerpool.Worker
	if rf, ok := ret.Get(0).(func(context.Context) runnerpool.Worker); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runnerpool.Worker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
